
version: 2.1

jobs:
  fail-with-default-shell:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - run:
          name: "Should pass"
          command: "true"
      - run:
          name: "Should fail"
          command: "false"
  fail-with-bare-bash:
    shell: bash
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - run:
          name: "Should pass"
          command: "true"
      - run:
          name: "Should fail"
          command: "false"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - fail-with-default-shell
      - fail-with-bare-bash
